#! /bin/bash

PARAMS=(`echo $*`)
NPARAMS=$#

if [[ $NPARAMS == 0 && -f .zipme ]]
then
  PARAMS=(`cat .zipme`)
elif [[ $NPARAMS == 0 ]]
then
  touch .zipme
fi

ZIP=${PARAMS[0]}
FILES=${PARAMS[@]:1}

for file in $FILES
do
  if [[ ! -e $file ]]
  then

    echo "zip-me: File \""$file"\" not found"
    exit 2
  fi
done

zip $ZIP $FILES -r
